public class Cons {
   public static final String[] ADVICE = new String[]{"Tẩy chay trò chơi không lành mạnh,", "Cự tuyệt trò chơi không bản quyền.", "Chú ý bảo vệ sức khỏe khi chơi,", "Chơi cẩn thận coi chừng bị lừa.", "Chơi đúng mức kích thích trí não", "Mải chơi game tổn hại sức khỏe.", "Sắp xếp thời gian hợp lý,", "Hưởng thụ cuộc sống lành mạnh."};
   public static final String FUNCTION_MAINTENANCE = "Chức năng này đang bảo trì.";
   public static final String RESOURCE_UI_1 = "/ui_1.pkg";
   public static final char[] Character = new char[]{'-', '(', ')', '~', '"', '/', '&', '*', '@', '.', '?', '!', '#', '_', ',', ':', ';', '%', '=', '+', '<', '>', '\'', '\\', '[', ']', '{', '}', '。', '，', '、', '：', '“', '”', '’', '？', '！', '【', '】', '《', '》', '…'};
   public static final byte CHARACTER_LOGIN = 1;
   public static final byte CHARACTER_NICKNAME = 2;
   public static final byte CHARACTER_OTHER = 3;
   public static final byte CHARACTER_TOUCH_ENROL = 4;
   public static final byte CHARACTER_LENGTH = 5;
   public static final byte EXAMINE_NUM = 6;
   public static final String[] MAIN_MENU_STR_LOGIN = new String[]{"Đăng nhập", "Đăng ký", "Đăng ký nhanh", "Quên mật khẩu", "Thiết Lập", "Hỗ Trợ", "Liên quan", "Thoát　", "Nạp thẻ"};
   public static final String[] MAIN_MENU_STR_NONE_LOGIN = new String[]{"Đăng ký nhanh", "Đăng nhập", "Đăng ký", "Quên mật khẩu", "Thiết lập", "Hỗ trợ", "Liên quan", "Thoát", "Nạp thẻ"};
   public static final String[] MAIN_CM_MENU_STR = new String[]{"Đăng nhập", "Đăng ký nhanh", "Đăng ký", "Các game khác", "Thiết lập dây mạng", "Hỗ trợ", "Liên quan", "Thoát", "Chuyên khu điểm số"};
   public static final String[] PIC_QUALITY_STR = new String[]{"Hight", "Medium", "Low"};
   public static final int MAIN_MENU_SHOW_ITEM = 5;
   public static final String[] SMS_HEADER_STR = new String[]{"Gate", "Mobile", "Vina", "Viettel", "Vcoin"};
   public static final String[] C_STR = new String[]{"Thao tác", "Trở về", "Xác định", "Hủy bỏ", "Thoát", "Thoát", "Chi tiết", "So sánh", "Tra xem", "Lỗi sai", "Nhận", "Hoàn thành", "Xem vật phẩm", "Sắp xếp", "Gửi thư", "Đồng ý đấu giá", "Nhận vật phẩm về", "Điêu Khắc bảo thạch", "Chọn vật phẩm", "Giải thích điêu khắc", "Thiết lập Vật phẩm", "Khai phong trang bị", "Giải thích khai phong", "Thiết lập lại vật phẩm", "Hợp thành nguyên thạch", "Giải thích hợp thành"};
   public static final byte UI_TITLE = 0;
   public static final byte UI_LABEL = 1;
   public static final byte UI_TEXTFIELD = 2;
   public static final byte UI_RADIO = 3;
   public static final byte UI_PICTURE = 4;
   public static final byte UI_PANEL = 5;
   public static final byte UI_TREE = 6;
   public static final byte UI_FOLDER = 7;
   public static final byte UI_GRID = 8;
   public static final byte UI_LINE = 9;
   public static final byte UI_LIST = 10;
   public static final byte UI_TEXTAREA = 11;
   public static final byte UI_TABLE = 12;
   public static final byte UI_NULL = 99;
   public static final int FORM_SAVE_QUIT = 0;
   public static final int FORM_SAVE_COMMAND = 1;
   public static final int FORM_SAVE_FORM = 2;
   public static final int FORM_SAVE_NONE = 3;
   public static final int FORM_SAVE_CHAIN = 4;
   public static final int FORM_SAVE_FIRST = 5;
   public static final int FORM_SAVE_DELETE = 6;
   public static final int FORM_SAVE_CHAT = 7;
   public static final String[] MENU_STR;
   public static final String[] MENU_PACKAGE_GOODS_STR;
   public static final String[] MENU_PACKAGE_EQUIP_STR;
   public static final int[] MENU_PACKAGE_GOODS_INNS;
   public static final int[] MENU_PACKAGE_EQUIP_INNS;
   public static final String[] MENU_SHOP_STR;
   public static final String[] MENU_CHANGE_GOODS_SHOP_STR;
   public static final String[] MENU_BLACK_STR;
   public static final String[] MENU_EQUIP_UP_STR;
   public static final String[] MENU_PLAYER_INFOMATION;
   public static final String[] MENU_STORAGE_EXPAND_STR;
   public static final String[] MENU_EQUIP_DOWN_STR;
   public static final String[] MENU_DESIGNATION;
   public static final int[] MENU_DESIGNATION_INNS;
   public static final String[] MENU_CHOOSE_REN;
   public static final String[] MENU_ESTABLISH_PART;
   public static final String[] MENU_TALK_LIST;
   public static final String[] MENU_GAME_MOUNT;
   public static final String[] MENU_GAME_MOUNT1;
   public static final String[] MENU_TRADE_SELF_NONE_STR;
   public static final String[] MENU_TRADE_SELF_WP_STR;
   public static final String[] MENU_TRADE_SELF_FINISH;
   public static final String[] MENU_TRADE_OTHER_STR;
   public static final String[] MENU_CHANGE_STR;
   public static final String[] MENU_CHANGE_STR2;
   public static final String[] MENU_TRADE_OTHER_NULL_FINISH;
   public static final String[] MENU_MAIL_INBOX;
   public static final String[] PHYLE;
   public static final String[] PROFESSION;
   public static final String[] SEIZING_EXPLAIN;
   public static final String[] ESTABLISH_INTRODUCE;
   public static final String[] SIMPLENESS_INTRODUCE;
   public static final String[] ADDRESSEE;
   public static final String[] SUBJECT;
   public static final String[] ACCESSORY;
   public static final String[] ACCESSORY1;
   public static final String[] AUCTION_SALE_SUBMENU;
   public static final String[] MENU_GEM_SETTING;
   public static final String[] MENU_GEM_VIEW;
   public static final String[] MENU_GEM_FINISH;
   public static final String[] MENU_PERSONAL_ENEMY;
   public static final String[] MENU_PERSONAL_ENEMY_OFFLINE;
   public static final String[] MENU_PERSONAL_APPEND;
   public static final String[] MENU_UNSEAL;
   public static final String[] MENU_UNSEAL_SUCCEED_LOST;
   public static final String[] MENU_GEMCARVE;
   public static final String[] MENU_GEMCARVE_1;
   public static final String[] MENU_GEMCARVE_2;
   public static final String[] MENU_GEMCARVE_3;
   public static final String[] MENU_UNSEAL_1;
   public static final String[] MENU_UNSEAL_2;
   public static final String[] MENU_UNSEAL_3;
   public static final String[] MENU_SYNTHESIZE_1;
   public static final String[] MENU_SYNTHESIZE_2;
   public static final String[] MENU_SYNTHESIZE_3;
   public static final String[] MENU_GEM_UNCHAIN_1;
   public static final String[] MENU_GEM_UNCHAIN_2;
   public static final String[] MENU_GEM_UNCHAIN_3;
   public static String[] SERVICE_STR;
   public static final String DATABANK = "name_password";
   public static final String GAMEMOUNT = "gamemount";
   public static final String GAME_KEY_SAVE = "gameKey";
   public static final String KEY_SET = "keyValue";
   public static final String SHOWSETUP_SAVE = "showSetup";
   public static final String VIDEOSETUP_SAVE = "videoSetup";
   public static final String PVPSETUP_SAVE = "pvpSetup";
   public static final String QUANTITY_SAVE = "quantitySetup";
   public static final String CHARACTER_DEBARKATION = "debarkation";
   public static final String CHARACTER_DEBARKATION1 = "debarkation1";
   public static final String SERVERLIST = "serverlist";
   public static final String LOGIN_TYPE_SAVE = "login_type";
   public static final byte SHOWSETUP_NUM = 5;
   public static final int COLOR_STYLE_1 = 15317892;
   public static final int COLOR_STYLE_2 = 2004107;
   public static final int COLOR_STYLE_3 = 8874039;
   public static final int COLOR_STYLE_4 = 11730944;
   public static final int COLOR_STYLE_5 = 9079434;
   public static final int COLOR_STYLE_6 = 45329;
   public static final int COLOR_KUANG_1 = 6503953;
   public static final int COLOR_KUANG_2 = 600869;
   public static final int COLOR_KUANG_3 = 2234114;
   public static final int COLOR_KUANG_4 = 5111808;
   public static final int COLOR_KUANG_5 = 3421236;
   public static final int COLOR_KUANG_6 = 18183;
   public static int COLOR_BACKGROUND;
   public static int COLOR_FONT_1;
   public static int COLOR_PANEL_BORDER_1;
   public static int COLOR_PANEL_BORDER_2;
   public static int COLOR_PANEL_BG;
   public static int COLOR_PANEL_BORDER_3;
   public static int COLOR_SCROLL_LINE_1;
   public static int COLOR_SCROLL_LINE_2;
   public static int COLOR_SCROLL_LINE_3;
   public static int COLOR_TITLE_BORDER_1;
   public static int COLOR_TITLE_BORDER_2;
   public static int COLOR_TITLE_BG;
   public static int COLOR_TITLE_MSG;
   public static int COLOR_FOLDER_BORDER_1;
   public static int COLOR_FOLDER_BORDER_2;
   public static int COLOR_FOLDER_BG;
   public static int COLOR_FOLDER_SEL_BG;
   public static int COLOR_FOLDER_UNSEL_BG;
   public static int COLOR_FOLDER_SEL_BORDER;
   public static int COLOR_FOLDER_FONT;
   public static int COLOR_TEXT_BORDER;
   public static int COLOR_TEXT_BG;
   public static int COLOR_TEXT_FONT;
   public static int COLOR_RADIO_CORE;
   public static int COLOR_RADIO_UNSEL_CORE_BG;
   public static int COLOR_RADIO_UNUSE_CORE_BG;
   public static int COLOR_RADIO_INDEX_ITEM_BG;
   public static int COLOR_PIC_PLAYER_BORDER_1;
   public static int COLOR_PIC_PLAYER_BORDER_2;
   public static int COLOR_PIC_PLAYER_BG;
   public static int COLOR_PIC_FRAME_BORDER;
   public static int COLOR_PIC_FRAME_BG;
   public static int COLOR_PIC_FRAME_DOT;
   public static int COLOR_PIC_FRAME_WORD;
   public static int COLOR_LABEL_BORDER;
   public static int COLOR_LABEL_BG;
   public static int COLOR_MENU_OUT_BORDER_1;
   public static int COLOR_MENU_OUT_BORDER_2;
   public static int COLOR_MENU_OUT_BORDER_3;
   public static int COLOR_MENU_INNER_BORDER_1;
   public static int COLOR_MENU_INNER_BORDER_2;
   public static int COLOR_MENU_INNER_BORDER_3;
   public static int COLOR_MENU_INNER_BORDER_4;
   public static int COLOR_MENU_BG;
   public static int COLOR_MENU_SEL_ITEM_BG;
   public static int COLOR_TABLE_TITLE_BG;
   public static int COLOR_TABLE_SEL_ITEM_BG;
   public static int COLOR_LINE;
   public static int COLOR_RIGHT_MENU_1;
   public static int COLOR_RIGHT_MENU_2;
   public static int COLOR_RIGHT_MENU_3;
   public static int COLOR_RIGHT_MENU_FONT;
   public static int COLOR_SKILL_BACKGROUND;
   public static int COLOR_SKILL_BORDER_1;
   public static int COLOR_SKILL_BORDER_2;
   public static int COLOR_SKILL_FRAME;
   public static int COLOR_SKILL_PANEL;
   public static int COLOR_TEAM_BACKGROUND;
   public static int COLOR_TEAM_BORDER_1;
   public static int COLOR_TEAM_BORDER_2;
   public static final byte REP_HATED = -3;
   public static final byte REP_HOSTILE = -2;
   public static final byte REP_UNFRIENDLY = -1;
   public static final byte REP_NEUTRAL = 0;
   public static final byte REP_FRIENDLY = 1;
   public static final byte REP_HONORED = 2;
   public static final byte REP_REVERED = 3;
   public static final byte REP_EXALTED = 4;
   public static final int[] OBJ_NAME_COLOR;
   public static int COLOR_PLAYER_EXPERIENCE;
   public static final byte NPC_TASKMARK_GRAYi = 1;
   public static final byte NPC_TASKMARK_YELLOWi = 4;
   public static final byte NPC_TASKMARK_BLUEi = 3;
   public static final byte NPC_TASKMARK_GRAYj = 2;
   public static final byte NPC_TASKMARK_YELLOWj = 6;
   public static final byte NPC_TASKMARK_BLUEj = 5;
   public static final int[] TASK_SHOW_COLOR;
   public static final String TEST_STRING = "Công năng này tạm thời chưa có.";
   public static final int[][] COLOR_GRID_FRAME_BG;
   public static final int[] COLOR_STUFF_QUALITY;
   public static final int UI_FORM_WIDTH = 176;
   public static final int UI_FORM_HEIGHT = 208;
   public static final int TOP_MAIL_SUCCEED = -3;
   public static final int TOP_GEM_CARVE_LEFT = -4;
   public static final int TOP_GEM_CARVE_RIGHT = -4;
   public static final int TOP_NUSEAL_SUCCEED_LOST = -5;
   public static final int TOP_GEM_CARVE_1 = -6;
   public static final int TOP_GEM_CARVE_2 = -7;
   public static final int TOP_GEM_CARVE_3 = -8;
   public static final int TOP_GEM_CARVE_4 = -9;
   public static final int TOP_NUSEAL = -10;
   public static final int TOP_SYNTHESIZE = -11;
   public static final int TOP_SYNTHESIZE_ERROR_1 = -12;
   public static final int TOP_GEM_UNCHAIN_1 = -13;
   public static final int TOP_GEM_UNCHAIN_2 = -14;
   public static final int TOP_GAMBLE = -18;
   public static final int TOP_AFRESH_CHARACTER = -19;
   public static final int TOP_RENEW = -20;
   public static final int TOP_QUIT_UI = -21;
   public static final int TOP_BESET_失败 = -22;
   public static final int TOP_INCREMENT_NOTE = -23;
   public static final int TOP_TOUTIST_AGAINLOGIN = -24;
   public static final int TOP_TOUTIST_SUCCEED = -25;
   public static final int TOP_GOODS_NOTFOUND = -26;
   public static final int TOP_YOUKE_ZHUANZHENG = -27;
   public static final int TOP_YOUKE_NOTARIZE = -28;
   public static final int TOP_FARM_DEPOT_ALLCADGE = -29;
   public static final int TOP_ENROL = -30;
   public static final int TOP_CELERITY_ENROL_LEFT = -31;
   public static final int TOP_RIGHTCMD_RENEW = -12;
   public static final int TOP_FARM_REDUCE = -16;
   public static final int TOP_CELERITY_ENROL_RIGHT = -17;
   public static final int TOP_SHOP__RIGHT_SALE_CANCEL = -18;
   public static final int TOP_NOTHING = -120;
   public static final int TOP_TASK_BUY = -250;
   public static final int TOP_CHARGE_CONTINUE = -260;
   public static final int EQUIP_非装备 = 0;
   public static final int EQUIP_主副手 = 1;
   public static final int EQUIP_戒指 = 2;
   public static final int EQUIP_饰品 = 3;
   public static final int EQUIP_主手 = 4;
   public static final String[] AUCTION_ALL_LIST;
   public static final String[] AUCTION_WEAPON_LIST;
   public static final String[] AUCTION_ARMOR_LIST;
   public static final String[] AUCTION_MATERIAL_LIST;
   public static final String[] AUCTION_EXPEND_LIST;
   public static final String[] AUCTION_GEM_LIST;
   public static final String[] AUCTION_QUALITY_LIST;
   public static final String[] FORG_ALL_LIST;
   public static final String[] FORG_WEAPON_LIST;
   public static final String[] skill_CONDITION;
   public static String[] strHelpTitles;
   public static String[] strHelpContentMainMenu;
   public static String[] CMContent;
   public static String[] UNIContent;
   public static String[] strPointsTitles;
   public static String[] netContent;
   public static String prefixPhongThan;
   public static final int L_RECHARD_SMS = -32;

   static {
      MENU_STR = new String[]{C_STR[0], C_STR[1]};
      MENU_PACKAGE_GOODS_STR = new String[]{"Sử dụng", "Tra xem", "Di chuyển", "Chỉnh lý", "Bỏ"};
      MENU_PACKAGE_EQUIP_STR = new String[]{"Trang bị", "Tra xem", "Di chuyển", "So sánh", "Chỉnh lý", "Bỏ"};
      MENU_PACKAGE_GOODS_INNS = new int[]{3, 2, 3, 3, 3};
      MENU_PACKAGE_EQUIP_INNS = new int[]{3, 2, 3, 2, 3, 3};
      MENU_SHOP_STR = new String[]{"Mua vật phẩm", C_STR[6], C_STR[7]};
      MENU_CHANGE_GOODS_SHOP_STR = new String[]{"Xem vật phẩm", "Đổi vật phẩm"};
      MENU_BLACK_STR = new String[]{C_STR[6], "Tắt lá chắn", "Thêm vào ds đen"};
      MENU_EQUIP_UP_STR = new String[]{"Trang bị"};
      MENU_PLAYER_INFOMATION = new String[]{"Sửa thông tin"};
      MENU_STORAGE_EXPAND_STR = new String[]{"Xem", "Sử dụng"};
      MENU_EQUIP_DOWN_STR = new String[]{"Mua", "Tra xem", "Tháo", "So sánh"};
      MENU_DESIGNATION = new String[]{"Nhân vật tăng cấp", "Đổi tên"};
      MENU_DESIGNATION_INNS = new int[]{3, 2, 3};
      MENU_CHOOSE_REN = new String[]{"Xác định nhân vật"};
      MENU_ESTABLISH_PART = new String[]{"Tạo nhân vật"};
      MENU_TALK_LIST = new String[]{"Chat"};
      MENU_GAME_MOUNT = new String[]{"Thay đổi phong cách", "Mở tăng điểm", "Thoát khỏi thiết lập"};
      MENU_GAME_MOUNT1 = new String[]{"Thay đổi kết nối", "Thoát khỏi thiết lập"};
      MENU_TRADE_SELF_NONE_STR = new String[]{"Đặt", "Tái thiết lập", "Khóa"};
      MENU_TRADE_SELF_WP_STR = new String[]{"Xem", "Lấy về", "Tái thiết lập", "Khóa"};
      MENU_TRADE_SELF_FINISH = new String[]{"Xem", "Giao dịch"};
      MENU_TRADE_OTHER_STR = new String[]{"Chọn vật phẩm", "Thư", "Xem"};
      MENU_CHANGE_STR = new String[]{"Xem", "Chỉnh lý"};
      MENU_CHANGE_STR2 = new String[]{"Chỉnh lý"};
      MENU_TRADE_OTHER_NULL_FINISH = new String[]{"Giao dịch"};
      MENU_MAIL_INBOX = new String[]{"Xem thư", "Xóa thư", "Xóa hộp thư"};
      PHYLE = new String[]{"Nhân tộc", "Tiên tộc", "Yêu tộc", "Ma tộc"};
      PROFESSION = new String[]{"Kiếm khách", "Thích khách", "Đạo sĩ", "Y Sư", "Ảo thuật sư", "Ám vu"};
      SEIZING_EXPLAIN = new String[]{"Cố định tài khoản có thể đảm bảo an toàn cho tài khoản của bạn. Thao tác cố định áp dụng hình thức xác nhận qua tin nhắn, nếu như tài khoản của bạn đã cố định thì không cần thực hiện lại.", "Giải trừ cố định có thể giải trừ cố định tài khoản và trạng thái cố định. Thao tác này dùng cách gửi tin nhắn để xác nhận, cần sử dụng điện thoại chính gửi tin nhắn thì mới tiến hành thao tác thành công.", "Nếu như tài khoản đã cố định, thao tác này có thể thông qua tin nhắn để xác nhận có thể tìm lại mật khẩu bị quên. cần sử dụng điện thoại chính gửi tin nhắn thì mới tiến hành thao tác thành công."};
      ESTABLISH_INTRODUCE = new String[]{"Chiến loạn tam giới sau 1 ngàn năm, con người dưới sự giúp đỡ của tiên giới, trình độ văn minh đã cực kỳ phát triển, nhân gian đâu đâu cũng thấy cảnh phồn vinh, Tiên tộc vì 1500 năm trước chưa từng trảm quyết Tam Thi, phạm phải sát giới, làm giảm thành quả tu luyện của mình, cần phải hoàn thành trường hạo kiếp này mới có thể đắc đạo tu hành, phản bổn hoàn nguyên.", "Tam giới chiến loạn cả ngàn năm nay, Yêu Ma chưa bao giờ ngừng khát khao sức mạnh và máu tươi, Yêu Ma tộc trông có vẻ như trời êm biển lặng thật ra đang nuôi 1 âm mưu to lớn, bọn chúng âm thầm cấu kết với những người và tiên có tà niệm, dẫn dụ bọn họ đi vào con đường tà đạo, dần dần tích lũy sức mạnh, chờ đợi cơ hội để thực hiện kế hoạch tà ác của chúng.", "Nhân tộc là chúng tộc lớn nhất, số lượng đông nhất, chiếm nhiều thuộc địa đại lục nhất. Thiên phú của nhân tộc tương đối bình thường, năng lực chia đều. Nhưng chính vì không có gì đặc biệt con người vô cùng cố gắng học tập những điều xung quanh, cộng thêm khả năng thích ứng mạnh mẽ, lấy cần cù bù thông minh, con người từ từ tranh giữ cả 1 vùng trời.", "Tiên tộc là chủng tộc cổ xưa nhất, lớn mạnh nhất, có sức sống vô tận, từng là người quản lý tối cao của thế giới. Tiên tộc pháp thuật thần kỳ từ khi mới sinh, có thể chỉ đá thành vàng, hô phong hoán vũ, trong chiến đấu có sức sát thương mạnh mẽ. Khuyết điểm duy nhất là trời sinh thể chất yếu đuối, không có sở trường tấn công ngoại công.", "Yêu tộc do tất cả các dị quái có linh tính trải qua ngàn năm tu hành tiến hóa mà thành. Để có được bản thể, chúng  hấp thu lâu dài tinh hoa nhật nguyệt, cho đến khi hóa thành hình người. Hoàn cảnh sinh sống khắc nghiệt khiến chúng thường xuyên đi lại giữa ranh giới sống và chết. Yêu tộc số lượng không nhiều, tính tình tham lam xảo trá, chưa từng có chủng tộc nào sùng bái sức mạnh như yêu tộc.", "Ma tộc là chủng tộc cổ xưa nhất sinh ra cùng thời với Tiên tộc, tính tình tàn bạo hiếu sát, điên cuồng dã man, cơ bắp cường tráng như sắt thép, thể lực siêu phàm quái lạ. Thiên tư ngu muội nên chúng không biết phép thuật, nhưng 1 số các ma tộc tương đối thông minh lại nắm bắt được 1 số chú thuật ngụy dị đời đời truyền cho nhau.", "Kiếm khách chính là 1 chức nghiệp đầy cảm giác tự hào, họ gánh vác trách nhiệm trừ gian diệt ác và bảo vệ đồng đội, kiếm khách có thể hai tay sử dụng vũ khí, kiếm、phủ、chùy, chủy thủ, thuẫn bài, vũ khí loại lớn món nào cũng tinh thông, có thể trang bị trọng giáp để tăng vốn sinh tồn cho thích khách. Kiếm khách sử dụng các loại chiêu thức vũ khí hoa lệ, thể lực dồi dào và tinh thần thượng võ.", "Thích khách là 1 chức nghiệp đầy tính khiêu khích và thú vị, kỹ năng đẹp đẽ, hành tung kỳ bí khiến chức nghiệp thích khách cứ như 1 câu đố bí ẩn. Thích khách có thể 2 tay sử dụng vũ khí, kiếm, chủy thủ món nào cũng tinh thông, có thể trang bị giáp da để tăng tính linh hoạt. Thần long thấy đầu không thấy đuôi, lấy đầu tướng địch giữa vạn quân như lấy đồ trong túi.", "Đạo sĩ là 1 chức nghiệp bác đại tinh thông, các đạo sĩ thông thường đều thong dong tự tại, bế quan tu luyện. Với thân hình mảnh khảnh đạo sĩ chỉ có thể khoát lên người áo vải, vũ khí cũng chỉ có kiếm, chủy thủ, pháp trượng, phó thủ có thể chọn lựa, nhưng những điều này hoàn toàn không ảnh hưởng đến sức chiến đấu của Đạo sĩ. Khi đối mặt với gian tà bọn họ sẽ không nể tình mà dùng những pháp thuật mạnh mẽ tấn công, trong nháy mắt, tất cả đều tan tành mây khói.", "Y sư là chức nghiệp thần thánh, chăm sóc người bị thương là thiên chức của họ, pháp thuật trị liệu nhanh chóng giúp họ bảo vệ đồng đội. Với thân hình mảnh khảnh y sư chỉ có thể khoát lên người giáp vải, vũ khí cũng chỉ có chùy, chủy thủ, pháp trượng có thể chọn lựa, nhưng dù là vậy cũng không hề ảnh hưởng tầm quan trọng của Y sư trong đội ngũ. Vẻ ngoài hiền từ nhưng không như nhược, nếu như có người ra tay với Y sư, bọn họ cũng có pháp thuật siêu mạnh để chế địch.", "Ảo thuật sư là 1 chức nghiệp tổ hợp, thiên biến vạn hóa, họ tinh thông các loại thể thuật, pháp thuật công kích lẫn trị liệu. Biến hóa khôn lường, quỷ thần khó đoán. Ảo thuật sư có thể hai tay sử dụng vũ khí, chùy, pháp trượng, phủ, chủy thủ, cự hình vũ khí món nào cũng tinh thông, có thể trang bị giáp da để cho ảo thuật sư linh hoạt hơn.", "Ám vu là 1 chức nghiệp đầy mùi tà khí, bọn họ vì để tăng cường thực lực của mình, thường bầu bạn với các phép thuật đen tối. Với thân hình mảnh khảnh ám vu chỉ có thể khoát lên người giáp vải, vũ khí cũng chỉ có kiếm, chủy thủ, pháp trượng có thể chọn lựa, nhưng dù vậy cũng không mảy may ảnh hưởng sức chiến đấu của ám vu. Ra tay nham nhiểm gần như là tàn nhẫn, bóng tối chỉ trong chốc lát là có thể ăn mòn linh hồn con người."};
      SIMPLENESS_INTRODUCE = new String[]{"Đồng minh giữa Nhân tộc và Tiên tộc...", "Trận doanh liên minh giữa Ma tộc và Yêu tộc...", "Năng lực chia đều, đoàn kết kiên cố, có khả năng thích ứng mạnh mẽ...", "Chủng tộc cổ xưa và thần bí, linh cảm rất mạnh, siêu việt bất phàm...", "Dị vật có linh tính, tham lam xảo trá, cực kỳ thèm khát sức mạnh...", "Chủng tộc nguyên thủy, tàn nhẫn man rợ, điên cuồng hiếu sát...", "Tượng trưng của sức mạnh, giết gian trừ ác, bảo vệ đồng đội...", "Hành tung bí hiểm, sở trường đánh lén, thần long thấy đầu không thấy đuôi...", "Pháp thuật mỹ lệ, đánh mạnh thủ yếu, sức bậc cực mạnh...", "Tâm hoài chúng sinh, cứu nguy phò nan, vô cùng kiên nhẫn...", "Tinh thông các loại kỹ năng, thiên biến vạn hóa, thần quỷ khôn lường...", "Kỹ năng tà ác tàn nhẫn, ra tay ác độc, ăn mòn nhân cách con người..."};
      ADDRESSEE = new String[]{"Danh sách bạn bè", C_STR[13], C_STR[14]};
      SUBJECT = new String[]{C_STR[13], C_STR[14]};
      ACCESSORY = new String[]{"Đặt vật phẩm", "Tái thiết lập vật phẩm", C_STR[14]};
      ACCESSORY1 = new String[]{C_STR[12], C_STR[16], "Tái thiết lập vật phẩm", C_STR[14]};
      AUCTION_SALE_SUBMENU = new String[]{C_STR[15], C_STR[16]};
      MENU_GEM_SETTING = new String[]{"Khảm nạm bảo thạch", C_STR[8]};
      MENU_GEM_VIEW = new String[]{"Xem bảo thạch", "Thay bảo thạch"};
      MENU_GEM_FINISH = new String[]{"Khảm nạm"};
      MENU_PERSONAL_ENEMY = new String[]{C_STR[6], "Xóa kẻ thù", "Thêm kẻ thù", "Dịch chuyển"};
      MENU_PERSONAL_ENEMY_OFFLINE = new String[]{C_STR[6], "Xóa kẻ thù", "Thêm kẻ thù"};
      MENU_PERSONAL_APPEND = new String[]{"Thêm kẻ thù"};
      MENU_UNSEAL = new String[]{C_STR[12], C_STR[21]};
      MENU_UNSEAL_SUCCEED_LOST = new String[]{C_STR[12]};
      MENU_GEMCARVE = new String[]{C_STR[17]};
      MENU_GEMCARVE_1 = new String[]{C_STR[18], C_STR[17], C_STR[19]};
      MENU_GEMCARVE_2 = new String[]{C_STR[20], C_STR[6], C_STR[17], C_STR[19]};
      MENU_GEMCARVE_3 = new String[]{C_STR[23], C_STR[6], C_STR[17], C_STR[19]};
      MENU_UNSEAL_1 = new String[]{C_STR[20], C_STR[6], C_STR[21], C_STR[22]};
      MENU_UNSEAL_2 = new String[]{C_STR[18], C_STR[21], C_STR[22]};
      MENU_UNSEAL_3 = new String[]{C_STR[23], C_STR[6], C_STR[21], C_STR[22]};
      MENU_SYNTHESIZE_1 = new String[]{C_STR[18], C_STR[24], C_STR[25]};
      MENU_SYNTHESIZE_2 = new String[]{C_STR[23], C_STR[6], C_STR[24], C_STR[25]};
      MENU_SYNTHESIZE_3 = new String[]{C_STR[20], C_STR[6], C_STR[24], C_STR[25]};
      MENU_GEM_UNCHAIN_1 = new String[]{C_STR[18], "Giải trừ bảo thạch", "Giải thích giải trừ"};
      MENU_GEM_UNCHAIN_2 = new String[]{C_STR[23], C_STR[6], "Giải trừ bảo thạch", "Giải thích giải trừ"};
      MENU_GEM_UNCHAIN_3 = new String[]{C_STR[20], C_STR[6], "Giải trừ bảo thạch", "Giải thích giải trừ"};
      SERVICE_STR = new String[]{"Vấn đề bản đồ", "Vấn đề chiến đấu", "Vấn đề vật phẩm", "Vấn đề nhân vật", "Vấn đề khác"};
      COLOR_BACKGROUND = 4864570;
      COLOR_FONT_1 = 4864570;
      COLOR_PANEL_BORDER_1 = 7755053;
      COLOR_PANEL_BORDER_2 = 14728078;
      COLOR_PANEL_BG = 16575691;
      COLOR_PANEL_BORDER_3 = 6045209;
      COLOR_SCROLL_LINE_1 = 6045209;
      COLOR_SCROLL_LINE_2 = 9333051;
      COLOR_SCROLL_LINE_3 = 14728078;
      COLOR_TITLE_BORDER_1 = 7755053;
      COLOR_TITLE_BORDER_2 = 14728078;
      COLOR_TITLE_BG = 16575691;
      COLOR_TITLE_MSG = 12490855;
      COLOR_FOLDER_BORDER_1 = 7755053;
      COLOR_FOLDER_BORDER_2 = 16637613;
      COLOR_FOLDER_BG = 6045209;
      COLOR_FOLDER_SEL_BG = 16637613;
      COLOR_FOLDER_UNSEL_BG = 12490855;
      COLOR_FOLDER_SEL_BORDER = 6045209;
      COLOR_FOLDER_FONT = 6045209;
      COLOR_TEXT_BORDER = 6045209;
      COLOR_TEXT_BG = 14602158;
      COLOR_TEXT_FONT = 6045209;
      COLOR_RADIO_CORE = 6045209;
      COLOR_RADIO_UNSEL_CORE_BG = 16637613;
      COLOR_RADIO_UNUSE_CORE_BG = 12490855;
      COLOR_RADIO_INDEX_ITEM_BG = 5450263;
      COLOR_PIC_PLAYER_BORDER_1 = 6045209;
      COLOR_PIC_PLAYER_BORDER_2 = 16637613;
      COLOR_PIC_PLAYER_BG = 4864570;
      COLOR_PIC_FRAME_BORDER = 9333051;
      COLOR_PIC_FRAME_BG = 16637613;
      COLOR_PIC_FRAME_DOT = 13807232;
      COLOR_PIC_FRAME_WORD = 13807232;
      COLOR_LABEL_BORDER = 6045209;
      COLOR_LABEL_BG = 14728078;
      COLOR_MENU_OUT_BORDER_1 = 6045209;
      COLOR_MENU_OUT_BORDER_2 = 9333051;
      COLOR_MENU_OUT_BORDER_3 = 14728078;
      COLOR_MENU_INNER_BORDER_1 = 6045209;
      COLOR_MENU_INNER_BORDER_2 = 6045209;
      COLOR_MENU_INNER_BORDER_3 = 16637613;
      COLOR_MENU_INNER_BORDER_4 = 6045209;
      COLOR_MENU_BG = 16637613;
      COLOR_MENU_SEL_ITEM_BG = 4864570;
      COLOR_TABLE_TITLE_BG = 14728078;
      COLOR_TABLE_SEL_ITEM_BG = 5450263;
      COLOR_LINE = 6045209;
      COLOR_RIGHT_MENU_1 = 4864570;
      COLOR_RIGHT_MENU_2 = 14728078;
      COLOR_RIGHT_MENU_3 = 16575691;
      COLOR_RIGHT_MENU_FONT = 6045209;
      COLOR_SKILL_BACKGROUND = 14602158;
      COLOR_SKILL_BORDER_1 = 6045209;
      COLOR_SKILL_BORDER_2 = 14728078;
      COLOR_SKILL_FRAME = 6045209;
      COLOR_SKILL_PANEL = 12490855;
      COLOR_TEAM_BACKGROUND = 0;
      COLOR_TEAM_BORDER_1 = 6045209;
      COLOR_TEAM_BORDER_2 = 12490855;
      OBJ_NAME_COLOR = new int[]{16711680, 16750080, 16776960, 65280};
      COLOR_PLAYER_EXPERIENCE = 16711424;
      TASK_SHOW_COLOR = new int[]{8882055, 16776960, 255};
      COLOR_GRID_FRAME_BG = new int[][]{{0, 11908533}, {18176, 48640}, {10329, 40191}, {5046385, 16711935}, {7356160, 16737792}, {7536640, 15007744}};
      COLOR_STUFF_QUALITY = new int[]{8224125, 16777215, 2192896, 1728767, 16711935, 16742400, 16711680};
      AUCTION_ALL_LIST = new String[]{"Tất cả vật phẩm", "Loại vũ khí", "Loại phòng cụ", "Loại nguyên liệu", "Loại tiêu hao", "Khác"};
      AUCTION_WEAPON_LIST = new String[]{"Tất cả vũ khí", "Đơn thủ kiếm", "Chủy thủ", "Pháp trượng", "Đơn thủ chùy", "Đơn  thủ phủ", "Cự hình vũ khí", "Phó thủ"};
      AUCTION_ARMOR_LIST = new String[]{"Tất cả phòng cụ", "Thuẫn bài", "Đầu", "Vai", "Thân", "Chân", "Oản", "Tay", "Lưng", "Chân", "Phi Phong", "Giới Chỉ", "Hạng Liên", "Pháp bảo"};
      AUCTION_MATERIAL_LIST = new String[]{"Tất cả nguyên liệu", "Vải", "Da", "Khoáng", "Thảo dược", "Bảo thạch", "Nguyên liệu ngưng nguyên"};
      AUCTION_EXPEND_LIST = new String[]{"Tất cả vật phẩm tiêu hao", "Thuốc phục hồi", "Thuốc đặc hiệu", "Quyển khai phong", "Bảo thạch điêu khắc phù", "Tu sửa vật phẩm", "Túi đồ vật phẩm", "Ngưng nguyên phù"};
      AUCTION_GEM_LIST = new String[]{"Tất cả bảo thạch", "Hồng Bảo Thạch", "Hoàng Bảo Thạch", "Lam Bảo Thạch", "Hồng bảo thạch nguyên thạch", "Hoàng bảo thạch nguyên thạch", "Lam bảo thạch nguyên thạch"};
      AUCTION_QUALITY_LIST = new String[]{"Phẩm chất Xám", "Phẩm chất Trắng", "Phẩm chất Lục", "Phẩm chất Lam", "Phẩm chất Tím", "Phẩm chất  Cam", "Phẩm chất  Đỏ"};
      FORG_ALL_LIST = new String[]{"Loại vũ khí", "Loại trọng giáp", "Loại bì giáp", "Loại giáp vải"};
      FORG_WEAPON_LIST = new String[]{"Kiếm", "Chùy", "Phủ", "Pháp trượng", "Chủy thủ", "Trọng hình vũ khí", "Phó thủ"};
      skill_CONDITION = new String[]{"", "Tiền game:", "Tiền mãnh mã:", "Kim nguyên bảo:", "Ngân nguyên bảo:", "Đồng nguyên bảo:", "Điểm vinh dự:", "Điểm đấu trường:", "Yêu cầu đặc biệt:", "Điểm kinh nghiệm:"};
      strHelpTitles = new String[]{"Giản lược trò chơi", "Quy tắc trò chơi", "Giải thích thao tác"};
      strHelpContentMainMenu = new String[]{"Ngàn vạn năm trôi qua nhanh như chớp mắt, lúc này đã đến thời kỳ Thương Chu, hạo kiếp của trời xanh sắp giáng xuống khu đất đầy sóng gió này. Tại nhân gian, hôn quân không lo xã tắc, mê muội nữ sắc, hoang phế triều chính, Chú Pháp Lạc, giết trung thần, chính sách hà khắc, bách tính ăn không đủ no, lưu li thất tán. Chu Võ Vương, con của Tây Bá Hầu, thuận thiên mệnh, được lòng dân, khởi binh thảo phạt bạo quân, PT đại chiến bắt đầu từ đây…… ", "Trong thế giới PT có 2 trận doanh lớn, mỗi 1 trận doanh đều có 2 chủng tộc, mối quan hệ đối lập giữa nhân tiên và yêu ma đối lập tạo nên nhiều cách chơi trong game.Trong game có Kiếm khách, thích khách, đạo sĩ, y sư, ảo thuật sư và ám vu 6 đại chức nghiệp, mỗi chức nghiệp đều có đặc sắc về kỹ năng và thiên phú riêng, giúp cho trò chơi có tính thu hút đặc biệt. Xoay quanh người chơi là sự thâm nhập bối cảnh được triển khai rộng rãi rõ ràng hơn, Các hạ có thể thám hiểm Natra đại náo long cung, cùng Khương Thái Công câu cá, mạo hiểm quốc chiến đánh chư hầu, Tổ đội bạn bè nhận ngọc phụ bản, thông qua quá trình cốt truyện trải nghiệm thú vui cao trào sống động, trong thế giới PT huyền ảo, có những trải nghiệm mới lạ mà Các hạ chưa từng thử qua.", "Giao diện trang chủ\n\n hướng trên：di chuyển vào khung trên\n hướng xuống：di chuyển vào khung dưới\n hướng trái：di chuyển sang khung trái\n hướng phải：di chuyển sang khung phải\n phím trái：Xác nhận\n phím phải：Trở về\n\n Trong giao diện game\n\n Phím lên：di chuyển lên trên\n phím dưới：di chuyển xuống dưới\n mũi tên trái：Di chuyển sang trái\n mũi tên phải：Di chuyển sang phải\n Phím giữa：Xác nhận/Tấn công\n＃Phím：Khóa\n＊Phím：Chat\n phím ９：chuyển thanh phím tắt\n phím ０：thay đổi chất lượng ảnh\n Phím trai：dựa theo hiển thị bối cảnh xác nhận thao tác tương ứng\n phím phải：dựa theo hiển thị bối cảnh thao tác tương ứng "};
      CMContent = new String[]{"Hệ thống tự động chọn dây mạng thích hợp với điện thoại. Có thể có máy không kết nối được, xin hãy chọn cách khác để nối mạng.", "Trong thiết lập dây mạng điện thoại điền CMWAP vào điểm kết nối, đều không có pass, máy chủ đại lý là 10.0.0.172, Cổng 80.", "Trong thiết lập dây mạng điện thoại điền CMNET vào điểm kết nối, đều không có pass."};
      UNIContent = new String[]{"Hệ thống tự động chọn dây mạng thích hợp với điện thoại. Có thể có máy không kết nối được, xin hãy chọn cách khác để nối mạng.", "Trong thiết lập dây mạng điện thoại điền UNIWAP vào điểm kết nối.", "Trong hiết lập dây mạng điện thoại điền UNINET vào điểm kết nối."};
      strPointsTitles = new String[]{"Nạp tiền", "Tra xem số dư", "Chi tiết", "Điểm hỗ trợ"};
      netContent = CMContent;
      prefixPhongThan = "pt";
   }
}
